<a href="https://colab.research.google.com/github/Preethikuppuri/Preethikuppuri/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
A = np.array(([[1, 2],
              [3, 4]]))
print(A)

[[1 2]
 [3 4]]


In [2]:
print(A.ndim)

1


In [3]:
print(A.size)

3


In [5]:
print(A.shape)

(3,)


In [6]:
print(A.dtype)

int64


In [10]:
B=np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [11]:
print(B.shape)

(2, 3)


In [16]:
print(B[1, 2])

6


In [24]:
print(B[1, :])

[4 5 6]


In [28]:
B[0,2]=8
print(B)

[[1 2 8]
 [4 5 6]]


In [31]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [32]:
np.random.rand(2,3)

array([[0.05105755, 0.11164842, 0.09020949],
       [0.89281503, 0.4158979 , 0.59692133]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
arr=np.array([[1,2,3,4,5]])
n1=np.repeat(arr,5, axis=0)
print(n1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [42]:
print(A**B)

[[   1    4 6561]
 [   1   32  729]]


In [43]:
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [50]:
arr=np.full((6,5),3)
print(arr)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [56]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [59]:
print(np.min(A, axis=1))

[1 3]


In [60]:
flattened = A.flatten()
print(flattened)

[1 2 3 4]


In [65]:
def dice_rolls(n):
  return np.random.randint(1,6,n)
roll=dice_rolls(6)
print(roll)

[2 2 4 1 3 2]


In [67]:
import numpy as np

data = np.random.randint(1, 100, 50)  # Generate 50 random numbers
print( data)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Min:", np.min(data), "Max:", np.max(data))


[ 1 58 43 11 84 56 60 38 42 63 12 42 23 74 21 79 23 99 56 31 44 45 14 76
 92 22 98 41 28  4 99 70  1 90 70 82 82 85 54 66 87 20 76 37 78 24 39 71
 35 15]
Mean: 51.22
Median: 49.5
Standard Deviation: 28.47826539661431
Min: 1 Max: 99


In [68]:

C = np.array([0, 10, 25, 37, 100])
F = (C * 9/5) + 32
K = C + 273.15

print("Celsius:", C)
print("Fahrenheit:", F)
print("Kelvin:", K)


Celsius: [  0  10  25  37 100]
Fahrenheit: [ 32.   50.   77.   98.6 212. ]
Kelvin: [273.15 283.15 298.15 310.15 373.15]


In [72]:
import numpy as np
import string

def generate_password(length):

    characters = list(string.ascii_letters + string.digits + string.punctuation)


    password = np.random.choice(characters, length)


    return "".join(password)

print("Generated Password:", generate_password(89))


Generated Password: PUgA6f{:_FoTrTOderm:5cK9(?j%qqL%8"c_bP}C%<*G;lbjTppS~BRM54ab[i%&uXw)>>Z.VZS~;hPHF_N\G>]~<


In [73]:
pip install kagglehub


In [74]:
import kagglehub

path = kagglehub.dataset_download("akalyasubramanian/dataset-for-numpypandas-operation")

print("Path to dataset files:", path)


100%|██████████| 35.0k/35.0k [00:00<00:00, 25.2MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/akalyasubramanian/dataset-for-numpypandas-operation/versions/1


In [77]:
import os


path = "/root/.cache/kagglehub/datasets/akalyasubramanian/dataset-for-numpypandas-operation/versions/1"

print("Files in dataset folder:", os.listdir(path))




Files in dataset folder: ['address.csv']


In [81]:
import numpy as np
import pandas as pd


df = pd.read_csv(csv_file)

print("Loaded Data:\n", df.head())

data_numeric = df.select_dtypes(include=['number']).to_numpy()

print(" NumPy Array:\n", data_numeric[:5])



Loaded Data:
    order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
Numeric Data as NumPy Array:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]]


In [90]:
print("Shape:", data.shape)
print("Size:", data.size)
print("Dimensions:", data.ndim)
print("Data Type:", data.dtype)
print("Total Elements:", data.size)


Shape: (50,)
Size: 50
Dimensions: 1
Data Type: int64
Total Elements: 50


In [95]:

print("Data Type :", df.dtypes)


Data Type : order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object


In [96]:
print("First 5 Rows:", df.head())

First 5 Rows:    order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   


In [99]:
print("📊 Stats:", df.describe())

📊 Stats:           order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000


In [107]:
print("Element at (1,0):", data[1, 0])


Element at (1,0): 58


In [110]:
print("First Row:", data[0])
print("First Column:", data[:, 0])
print("Element at (1,0):", data[1, 0])


First Row: [1]
First Column: [ 1 58 43 11 84 56 60 38 42 63 12 42 23 74 21 79 23 99 56 31 44 45 14 76
 92 22 98 41 28  4 99 70  1 90 70 82 82 85 54 66 87 20 76 37 78 24 39 71
 35 15]
Element at (1,0): 58


In [114]:

filtered_data = data[data[:, 0].astype(float) > 50]
print("Filtered Data (First Column > 50):", filtered_data)


Filtered Data (First Column > 50): [[58]
 [84]
 [56]
 [60]
 [63]
 [74]
 [79]
 [99]
 [56]
 [76]
 [92]
 [98]
 [99]
 [70]
 [90]
 [70]
 [82]
 [82]
 [85]
 [54]
 [66]
 [87]
 [76]
 [78]
 [71]]


In [115]:
sorted_data = df.sort_values(by=df.columns[0])
print("Sorted Data :", sorted_data.head())


Sorted Data :    order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
2         1         1                       Nantucket Nectar   
1         1         1                                   Izze   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
3                                                NaN     $2.39   
2                                            [Apple]     $3.39   
1                                       [Clementine]     $3.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
